name: Node.js CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [22]
    steps:
    - uses: actions/checkout@v6
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node }}
    - run: yarn install --frozen-lockfile --ignore-scripts
    - run: yarn coverage
    - name: Store coverage/lcov.info
      uses: actions/cache/save@v5
      with:
        path: coverage/lcov.info
        key: cache-${{ github.run_id }}-${{ github.run_attempt }}
    - run: yarn build

  sonarcloud:
    name: Run SonarQube Cloud Scan
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v6
    - name: Restore coverage/lcov.info
      uses: actions/cache/restore@v5
      with:
        path: coverage/lcov.info
        key: cache-${{ github.run_id }}-${{ github.run_attempt }}
        fail-on-cache-miss: true
    # Without this workaround, SonarQube Cloud reports a warning about an incorrect source path
    - name: Override coverage report source path for SonarQube Cloud
      run: sed -i 's@'$GITHUB_WORKSPACE'@/github/workspace/@g' coverage/lcov.info
    - name: SonarQube Cloud Scan
      uses: SonarSource/sonarqube-scan-action@v6
      with:
        args: >
          -Dsonar.organization=city-of-helsinki
          -Dsonar.projectKey=City-of-Helsinki_mvj-ui
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
